"""Tests for dom_parser.py

Auto-generated by scan_and_test.py -- covers importability
and pure functions discovered via AST analysis.
"""

import importlib.util
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _load_module():
    """Import dom_parser by file path."""
    filepath = PROJECT_ROOT / "specialized/dom_parser.py"
    spec = importlib.util.spec_from_file_location("dom_parser", filepath)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    # Patch sys.argv to prevent argparse from firing
    old_argv = sys.argv
    sys.argv = ["test"]
    try:
        spec.loader.exec_module(mod)
    except SystemExit:
        pass
    finally:
        sys.argv = old_argv
    return mod


@pytest.fixture(scope="module")
def mod():
    """Load the module once for all tests."""
    return _load_module()


class TestImport:
    def test_module_loads(self, mod):
        """Module imports without error."""
        assert mod is not None


class TestFunctions:
    def test_parse_html_exists(self, mod):
        """parse_html is callable."""
        assert hasattr(mod, "parse_html")
        assert callable(getattr(mod, "parse_html"))

    def test_parse_html_runs(self, mod):
        """parse_html executes without error."""
        result = mod.parse_html(html="")
        # Function returned without raising
        assert result is not None or result is None

    def test_find_element_exists(self, mod):
        """find_element is callable."""
        assert hasattr(mod, "find_element")
        assert callable(getattr(mod, "find_element"))

    def test_extract_dom_element_exists(self, mod):
        """extract_dom_element is callable."""
        assert hasattr(mod, "extract_dom_element")
        assert callable(getattr(mod, "extract_dom_element"))

    def test_extract_links_by_selector_exists(self, mod):
        """extract_links_by_selector is callable."""
        assert hasattr(mod, "extract_links_by_selector")
        assert callable(getattr(mod, "extract_links_by_selector"))

    def test_extract_text_exists(self, mod):
        """extract_text is callable."""
        assert hasattr(mod, "extract_text")
        assert callable(getattr(mod, "extract_text"))

    def test_extract_text_from_selector_exists(self, mod):
        """extract_text_from_selector is callable."""
        assert hasattr(mod, "extract_text_from_selector")
        assert callable(getattr(mod, "extract_text_from_selector"))

    def test_extract_attribute_exists(self, mod):
        """extract_attribute is callable."""
        assert hasattr(mod, "extract_attribute")
        assert callable(getattr(mod, "extract_attribute"))

    def test_extract_data_attributes_exists(self, mod):
        """extract_data_attributes is callable."""
        assert hasattr(mod, "extract_data_attributes")
        assert callable(getattr(mod, "extract_data_attributes"))

    def test_count_elements_by_tag_exists(self, mod):
        """count_elements_by_tag is callable."""
        assert hasattr(mod, "count_elements_by_tag")
        assert callable(getattr(mod, "count_elements_by_tag"))

    def test_get_max_depth_exists(self, mod):
        """get_max_depth is callable."""
        assert hasattr(mod, "get_max_depth")
        assert callable(getattr(mod, "get_max_depth"))

    def test_filter_elements_exists(self, mod):
        """filter_elements is callable."""
        assert hasattr(mod, "filter_elements")
        assert callable(getattr(mod, "filter_elements"))

    def test_find_elements_with_text_exists(self, mod):
        """find_elements_with_text is callable."""
        assert hasattr(mod, "find_elements_with_text")
        assert callable(getattr(mod, "find_elements_with_text"))


class TestIOFunctions:
    """I/O-heavy functions -- verify existence, skip execution."""

    def test_find_elements_exists(self, mod):
        """Module has find_elements."""
        assert hasattr(mod, "find_elements")

    def test_extract_links_exists(self, mod):
        """Module has extract_links."""
        assert hasattr(mod, "extract_links")

    def test_extract_images_exists(self, mod):
        """Module has extract_images."""
        assert hasattr(mod, "extract_images")
